#!/bin/bash

# Copyright (c) 2019-2020 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: git setupb [SLUG [ALIAS]]    Pushes a local branch (ALIAS) to a
                                    remote branch named prefix/SLUG; use
                                    once to set the upstream, then just
                                    push normally
       git setupb -h|--help         Print this message and exit
USAGE
    exit 0
fi

Bold=`tput bold`
Off=`tput sgr0`

Alias="${2:-${ALLGIT_BRANCH:-`git rev-parse --abbrev-ref HEAD`}}"
Slug="${1:-$Alias}"

if [ -z "$Alias" ]; then
    echo "Must specify a branch directly, using allgit, or the current branch" >&2
    exit 1
fi

Branch=`git branch --list "$Alias"`
if [ -z "$Branch" ]; then
    echo "$Alias: branch not found" >&2
    exit 1
fi

ConfigRemote=`git config bettergit.defaultremote`
: ${DefaultRemote:=${ConfigRemote:-"origin"}}  # REM: maybe use the first remote by default? `git remote | head -n1`

Upstream=`git rev-parse --abbrev-ref "$Alias@{upstream}" 2> /dev/null | sed -e "s:$DefaultRemote/::"`
if [ "$Upstream" ]; then
    echo "$Alias: already pointing to $Upstream" >&2
    exit 1
fi

if `echo "$Slug" | grep "/" - > /dev/null`; then
    git push -u "$DefaultRemote" "$Alias:$Slug"  # If slug is already prefixed, use as-is
    exit 0
fi

: ${BranchPrefix:=`git config bettergit.branchprefix`}
if [ -z "$BranchPrefix" ]; then
    BranchPrefix=`git config user.shortname`
    if [ -z "$BranchPrefix" ]; then
        BranchPrefix=`git config user.name | tr 'A-Z ' 'a-z_'`
    fi
    if [ -z "$BranchPrefix" ]; then
        BranchPrefix="$USER"
    fi
    echo "${Bold}Using prefix $BranchPrefix/${Off} set it with: git config --global bettergit.branchprefix 'users/abc'"
fi

BranchPrefix=`echo "$BranchPrefix"  | sed -e's:/$::'`  # Trim any trailing slash to ensure isn't doubled
git push -u "$DefaultRemote" "$Alias:$BranchPrefix/$Slug"

###
